[package]
authors = ["Aaron Power <theaaronepower@gmail.com>"]
name = "hermes"
version = "0.1.0"
[dependencies]
clap = "*"
encoding_rs_io = "0.1"
git2 = "*"
regex = "*"
tokei = "*"

[dev-dependencies]
assert_cmd = "*"
tempfile = "*"
